kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: client-persistent-volumeclaim
  namespace: localnet
spec:
  storageClassName: pv-demo 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi