apiVersion: v1
kind: Pod
metadata:
  name: client
  namespace: localnet
  labels:
    app: libra-client
    libra-node: "false"
spec:
  hostNetwork: true
  containers:
  - name: init
    image: pariwesh/thesis:client-1.0.0
    imagePullPolicy: IfNotPresent
    securityContext:
      runAsUser: 0 # To get permissions to write to /opt/libra/data
    command:
    - "bash"
    - "-c"
    - |
      while [ true ]; do
        sleep 500;
      done;
    volumeMounts:
      - mountPath: "opt/libra/modules"
        name: client-persistent-volumeclaim-name

  volumes:
    - name: client-persistent-volumeclaim-name
      persistentVolumeClaim:
       claimName: client-persistent-volumeclaim  